[versions]
compileSdk = "33"
minSdk = "21"
targetSdk = "33"

trueTimeVersionCode = "12"
trueTime = "4.0.0.alpha"
trueTimeRx = "3.5"

androidGradlePlugin = "8.0.2"
androidxAppCompat = "1.6.1"
androidxLifecycle = "2.6.0"
constraintlayout = "2.1.4"
kotlin = "1.8.10"
kotlinxCoroutines = "1.6.4"
kotlinInject = "0.6.1"
ksp = "1.8.10-1.0.9"
rxJava = "2.1.1"
spotless = "6.15.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]

truetime = { group = "com.github.instacart", name = "truetime-android", version.ref = "trueTime" }
truetime-rx = { group = "com.github.instacart.truetime-android", name = "library-extension-rx", version.ref = "trueTimeRx" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlin-inject-compiler = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlin-inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlinInject" }
rxjava-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxJava" }
